### ISSUE TITLE
Roadmap | Futures

### ISSUE THREAD

**Issue by myCrack** [myCrack/cuda_hilite_occurrences#8]
## Configuration
- [ ] Configuration from external file
- [ ] Lexer's overriding
- [x] Letter List
- [ ] Not a Letter List

### Source (with minimal length)
- [x] Symbol under caret
- [x] Selected text

### Occurrences
- [x] Exact match                           [`caret | selection`]
- [x] Case insensitive                      [`caret | selection`]
- [x] With trimmed spaces                          [`selection`]
- [x] On word bound

### Where?
- [x] Entire text
- [ ] Nearest N characters
- [ ] Current View

## Highlighting
- [x] Source
- [x] Occurrences
- [ ] Inexact Matches
